### ISSUE TITLE
Redirection to login not working

### ISSUE THREAD

**Issue by Tobi-De** [mblayman/django-denied#4]
Hello @mblayman,  hope you are doing well.

Thanks for releasing this,  I've always been looking for a package like this, one that makes the login required by default, I've never found something that worked for me but I really like the django-denied api.

So here is my issue, I can't get it to work 😆 , let me explain. 
I'm working on a project where most pages need authenticated users, I have django-denied configured, the authorized views using the `allow` decorator works fine but any other view (at this point none of my views use authorizers) redirects me to a blank page, I'm not sure if this is a bug or the intended behavior, I would expect to be redirected to the login page for views that are not explicitly authorized.

I have a working login page and a custom html template for my 403 page but neither of them are used, I always get a blank page.
I configured a brand new django project with django-denied to illustrate my problem, you can find it here https://github.com/Tobi-De/django_denied_test.

Last thing I would like to add, in the installation guide you should specify that the `LOGIN_URL` setting should be the path of the view and not its name, this django setting allows to use the view name instead of it path but that won't work with django-denied. Thanks

**Comment by mblayman** [comment]
@Tobi-De, thank you for the report and for including the sample project that illustrates the issue!

I checked out the test project, and the reason that it's getting a 403 is because the login view itself does not have an `allow` decorator. I didn't notice the problem on the app where I spawned this from because I have the `allow` decorator on the two includes that include my login views (which makes them exempt from the checking in the `DeniedMiddleware`). https://github.com/mblayman/homeschool/blob/main/project/urls.py#L15-L24 shows the lines (highlighted at the top and bottom) that allow my login views.

In the short term, you can add `allow` to your login view.

I think it's reasonable for the middleware to *always* allow the login views, so that decoration of that entry point into an app is not required. I also like your suggestion about improving the documentation of `LOGIN_URL` to record that it needs to be a path.

I'll try to get these things updated for a future version.

**Comment by mblayman** [comment]
I've released 1.1 which includes the fix for this issue.

**Comment by Tobi-De** [comment]
Thanks for the quick response and fix @mblayman, I appreciate it, big fan of django riffs and building a saas with django.

**Comment by Tobi-De** [comment]
I have authorized the login page and it works fine. I still get a blank page on all pages that don't use the `allow` decorator or an authorizer, if I'm not mistaken this is the intended behavior, right? If this is the case, why not do something like this instead 🤔  ?

```py
raise PermissionDenied()
```

**Comment by mblayman** [comment]
It could be that I did the wrong thing. 😁 I forgot that `PermissionDenied` can trigger a custom handler for a 403 page. Let me start a new issue to consider changing it.
